################################################################################
# mediawiki_first_time_config.rb
################################################################################
# Chef recipe, part of mediawiki cookbook
################################################################################
# Copyright 2012 CloudOpt, Inc.  All rights reserved.
################################################################################
# Author: Bill Whitson <bill@cloudopt.com>
################################################################################
# First time build of the MediaWiki database.  This should be run as an
# operational script following first time installation.
################################################################################

rightscale_marker :begin

################################################################################
# Build the database
################################################################################
# This calls the MediaWiki command line installer with arguments from inputs.
################################################################################

log "Configure MediaWiki Database: Starting"
execute "install.php" do
 command "php #{node[:mediawiki][:installation_directory]}/maintenance/install.php \
  --dbname #{node[:mediawiki][:db_name]} \
  --dbserver #{node[:mediawiki][:db_server_address]} \
  --dbtype #{node[:mediawiki][:db_type]} \
  --dbuser #{node[:mediawiki][:db_user_account]} \
  --dbpass #{node[:mediawiki][:db_user_password]} \
  --installdbpass #{node[:mediawiki][:db_root_password]} \
  --installdbuser #{node[:mediawiki][:db_root_account]} \
  --pass #{node[:mediawiki][:mediawiki_admin_password]} \
  --scriptpath #{node[:mediawiki][:installation_directory]} \ 
  --server http://#{node[:mediawiki][:dns_name]} \
  --confpath /var/tmp \
  #{node[:mediawiki][:site_name]} \
  #{node[:mediawiki][:mediawiki_admin_account]}"
  
end
log "Configure MediaWiki Database: Ending"

################################################################################
# Install getmwconfig.php
################################################################################
# This script gets variables from the MediaWiki generated LocalSettings.php.  It
# is not really a template; we're just treating it like a template in order to
# install it.
################################################################################
log "Install getmwconfig.php: Starting"
template "#{node[:mediawiki][:work_dir]}/getmwconfig.php" do
  source "getmwconfig.php"
  mode "0754"
  owner "root"
  group "root"
end

################################################################################
# Get values from the autogenerated LocalSettings.php
################################################################################
# Use getmwconfig.php to pull MediaWiki generated settings from the default
# LocalSettings.php file.
################################################################################

node[:mediawiki][:namespace] = `php /var/tmp/getmwconfig.php wgMetaNamespace`
node[:mediawiki][:secret_key] = `php /var/tmp/getmwconfig.php wgSecretKey`
node[:mediawiki][:upgrade_key] = `php /var/tmp/getmwconfig.php wgUpgradeKey`

################################################################################
# Set defaults to public IP address
################################################################################
# Set the DNS name for Mediawiki to the public IP address as a default.  This
# is not really what most users would want to run with, but it does ensure
# that MediaWiki produces usable links if no DNS name is entered.
################################################################################
log "Set defaults: Starting"
if node[:mediawiki][:dns_name] == 'Public IP'
  log "Setting DNS name to #{node[:cloud][:public_ips][0]}"
  node[:mediawiki][:dns_name] = node[:cloud][:public_ips][0]
end
if node[:mediawiki][:admin_email] == 'apache@Public IP'
  log "Setting admin email to apache@#{node[:cloud][:public_ips][0]}"
  node[:mediawiki][:admin_email] = node[:cloud][:public_ips][0]
end
log "DNS name: Ending"

log "Set defaults: Ending"


################################################################################
# Build configuration from templates
################################################################################
# Build LocalSettings.php from inputs.
################################################################################
log "Template config: Starting"
log "Template config: Using template LocalSettings.php.erb."
template "#{node[:mediawiki][:installation_directory]}/LocalSettings.php" do
  source "LocalSettings.php.erb"
  mode "0644"
  owner "root"
  group "root"
end

rightscale_marker :end
